### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by uzairahmad98** [priteshrnandgaonkar/CardsStack#17]
Hello,
I recently download your example project. when I embed my view controller in navigation controller it disable the scrolling. So, if i have 30 cards and I embed my controller in navigation controller it disable scrolling in collection view.
How to fix it?

Please help me.

**Comment by priteshrnandgaonkar** [comment]
Yes, I will look into it.

**Comment by uzairahmad98** [comment]
Thanks. so when should i expect the update?

**Comment by priteshrnandgaonkar** [comment]
You need to add `automaticallyAdjustsScrollViewInsets = false` in the `viewDidLoad` of the viewcontroller and it will work fine. I will update the example with this change. Thanks for raising the issue.

**Comment by priteshrnandgaonkar** [comment]
@uzairahmad98 did the change suggested worked? If not then reopen the issue.

**Comment by priteshrnandgaonkar** [comment]
For general understanding, this issue was related to the side effect of adding NavigationController, navigationcontroller changed the inset of the collectionview which lead to this bug. Have a look at this stackoverflow issue, http://stackoverflow.com/questions/18924431/ios-7-navigationcontroller-is-setting-the-contentinset-and-contentoffset-of-m
